# Generated by Django 5.2 on 2025-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.DurationField(help_text='Exemple 25 minutes, 00:25:00'),
        ),
    ]
