# Generated by Django 5.2 on 2025-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='warning',
            field=models.CharField(default='BE CAREFUL WHEN YOU EDITING INGREDIENT NAME, IT WILL BE EDITED IN ALL RECIPES ON THE SITE', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
