# Generated by Django 5.2 on 2025-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesAPI', '0002_ingredient_warning_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_steps',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='BE CAREFUL WHEN YOU EDITING INGREDIENT NAME, IT WILL BE EDITED IN ALL RECIPES ON THE SITE', max_length=50, unique=True),
        ),
    ]
