# Generated by Django 5.2 on 2025-05-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesAPI', '0002_alter_recipe_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='recipesAPI.category'),
        ),
    ]
