# Generated by Django 5.2 on 2025-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesAPI', '0004_alter_category_options_remove_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
